context:
  version: "6.17.0"

package:
  name: spectral-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@stoplight/spectral-cli/-/spectral-cli-${{ version }}.tgz
  sha256: fdff616155068111f5fe00cd06ae8fdb640630f1082ad1e59187d466af7039bf

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - spectral --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: JSON/YAML linter and support OpenAPI v3.1/v3.0/v2.0, and AsyncAPI v2.x
  homepage: https://github.com/stoplightio/spectral
  repository: https://github.com/stoplightio/spectral

extra:
  recipe-maintainers:
    - danielnachun
