context:
  version: "6.14.3"

package:
  name: spectral-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@stoplight/spectral-cli/-/spectral-cli-${{ version }}.tgz
  sha256: 804c2db75dc07f50c503e75b23833aec89bb6563f8a33e08d26bc8e0239fae31

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - spectral --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: JSON/YAML linter and support OpenAPI v3.1/v3.0/v2.0, and AsyncAPI v2.x
  homepage: https://github.com/stoplightio/spectral
  repository: https://github.com/stoplightio/spectral

extra:
  recipe-maintainers:
    - danielnachun
