context:
  version: "6.16.0"

package:
  name: spectral-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@stoplight/spectral-cli/-/spectral-cli-${{ version }}.tgz
  sha256: 05da62e983a5e9f4bbe7f1af06ad7212a2cf4213d096f92f10d8544c86fa2f13

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - spectral --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: JSON/YAML linter and support OpenAPI v3.1/v3.0/v2.0, and AsyncAPI v2.x
  homepage: https://github.com/stoplightio/spectral
  repository: https://github.com/stoplightio/spectral

extra:
  recipe-maintainers:
    - danielnachun
